### ISSUE TITLE
Adição no repositório da turma

### ISSUE THREAD

**Issue by rodrigolsouza** [ramidedantas/GCMS-2024-1#19]
Professor, perdoe meu atraso e me adicione no repositório da turma.  @ramidedantas

**Comment by ramidedantas** [comment]
@rodrigolsouza convite enviado.

**Comment by rodrigolsouza** [comment]
Pronto professor. Nome inserido no repositório da turma com sucesso!

**Comment by ramidedantas** [comment]
OK @rodrigolsouza, fechando chamado.
