### ISSUE TITLE
Adicionar como colaborador

### ISSUE THREAD

**Issue by ghost** [ramidedantas/GCMS-2024-1#7]
@ramidedantas 

Passo 4 da prática.

**Comment by ramidedantas** [comment]
@LuisLimaJr convite enviado

**Comment by ghost** [comment]
@ramidedantas 

Passo 5 da prática 1. Nome incluido no Readme.md.

**Comment by ramidedantas** [comment]
@LuisLimaJr ok, fechando chamado.
